### ISSUE TITLE
No lights are showing up in MacOS

### ISSUE THREAD

**Issue by lokanchung** [Jengamon/Launchpad-X-Bitwig-Script#26]
Scripts controlling lights (Session mode, drum pad mode) are not working in MacOS.

Tested on Big Sur, and had a report for the same problem in KVR forum.
https://www.kvraudio.com/forum/viewtopic.php?f=259&t=564952&start=45

Took some look and it's kinda nasty as lights sometimes work properly with debugger interruption.

**Comment by Jengamon** [comment]
From the forum post, the first port should be the DAW one (so it's flipped from the Moss setup). It should go:
- DAW Out 
- MIDI Out
- DAW In
- MIDI In

I have no clue what's happening. It could be that the ports are messed up (as the script only doesn't support autodetection on Mac, because I don't have a Mac...).

The script only uses the Bitwig API, so it should be completely cross-platform.

**Comment by lokanchung** [comment]
After updating Bitwig from 3.3.1 to 3.3.10 the issue was gone. Seems like Bitwig API had some issues.
