### ISSUE TITLE
Would this work with Lauchpad Pro MK3?

### ISSUE THREAD

**Issue by Fannon** [Jengamon/Launchpad-X-Bitwig-Script#27]
Hi,

I'm in the same situation than you that I do like driven by moss extension, but would also like to keep the launchpad default functionality. Especially since the Pro MK3 has some really cool stuff built in.

So it looks like this is excactly what this extension is doing? Just curious: How well would it work with a Pro MK3? Would it be hard to adjust / customize it towards it? I'm a developer as well, but haven't touched Java seriously since a decade.

I'm asking because it looks like there are some troubles to get this work. E.g.
![image](https://user-images.githubusercontent.com/470980/132092125-3c69e0be-3289-4437-8a72-cecd29486672.png)

**Comment by Jengamon** [comment]
If you're still interested in this, that particular error is because something is going wrong here: https://github.com/Jengamon/Launchpad-X-Bitwig-Script/blob/514eeceac81446de9456bb913954c7fcd9709707/src/main/java/io/github/jengamon/novation/surface/state/FaderLightState.java#L22-L25
or here:
https://github.com/Jengamon/Launchpad-X-Bitwig-Script/blob/514eeceac81446de9456bb913954c7fcd9709707/src/main/java/io/github/jengamon/novation/surface/state/PadLightState.java#L55-L58

**Comment by Jengamon** [comment]
Should be fixed now. Not sure of any other errors, as I don't have a ProMk3, but good luck!

**Comment by Fannon** [comment]
Hi @Jengamon ,

thanks for looking into it. I don't see the fix yet.. did you push it to this repo?
Then I can try out how it works with my ProMk3. 

In the meanwhile I tried creating my own controller script as well (https://github.com/Fannon/Launchpad-Pro-Mk3-Bitwig-Controller), but I'm not all too happy about its current state / quality. 
Maybe the lessons learned there help me a bit to understand your project better, though.
